name: TheNakedTruth
favicon: null
layout_spectrum: 0.4469539844430983
typography_spectrum: 0.4219160061329603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07945251138880849
  lightness: 0.36980423447676003
  saturation: 0.457319017034024
  rhythmicContrast: 0.3272606981918216
purpose: []
